### ISSUE TITLE
Instrucciones de instalacion / uso

### ISSUE THREAD

**Issue by Jujonet** [hectorespert/python-oligo#1]
Hola, Podrías escribir unas líneas acerca de la instalación y el uso?
No tengo claras las posibilidades...... ¿qué te devuelve?
- Consumo actual
- Consumo entre fechas

¿?¿?¿??¿

Muchas gracias y un saludo

**Comment by hectorespert** [comment]
En el [Readme](https://github.com/blackleg/python-oligo/blob/master/README.md) del proyecto tienes algunas lineas acerca de la instalación y del uso.
Actualmente y si sigue funcionando podrías obtener el consumo actual del contador inteligente.
