### ISSUE TITLE
./login.py: line 3: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by alsak0de** [hectorespert/python-oligo#11]
Hola Héctor; he encontrado tu proyecto y tengo curiosidad por echarlo a andar.
He probado tanto en mac como en linux y en ambos obtengo el mismo error:

from: can't read /var/mail/oligo
./login.py: line 3: syntax error near unexpected token `('
./login.py: line 3: `connection = Iber()'

¿alguna pista?

**Comment by auveele** [comment]
Hola,
yo me he cruzado hoy con este proyecto, también estoy interesado.

¿Has instalado el paquete de Oligo?
`pip install oligo `

**Comment by hectorespert** [comment]
Cerrada por falta de información
