### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by farconada** [hectorespert/python-oligo#12]
File "iberdrola.py", line 5, in <module>
    watt = connection.watthourmeter()
  File "/root/iot/python-oligo/oligo/iber.py", line 84, in watthourmeter
    return self.measurement()['power']

**Comment by pbalm** [comment]
Hola, veo el mismo problema. Lo he arreglado en un [pull request](https://github.com/hectorespert/python-oligo/pull/13).

Mientras tanto en vez de escribir 

`watt = connection.watthourmeter()`

Utiliza

`watt = connection.measurement()['consumption']`
