### ISSUE TITLE
ResponseException during login (iber.py line 33)

### ISSUE THREAD

**Issue by sgoetz** [hectorespert/python-oligo#15]
Seems like the rest api endpoint https://www.iberdroladistribucionelectrica.com/consumidores/rest/loginNew/login has an internal error (500) or is not available anymore. Could you please confirm if this is still working or if anything changed. It this a public api. Can not find any documentation at Iberdrola. Thank you.

 File "/usr/local/lib/python2.7/dist-packages/oligo/iber.py", line 33, in login
    raise ResponseException
oligo.exceptions.ResponseException

**Comment by pirracas77** [comment]
Same error here:
`  File "/usr/local/lib/python2.7/dist-packages/oligo/iber.py", line 33, in login
    raise ResponseException
oligo.exceptions.ResponseException
`

**Comment by cyberdie** [comment]
Same here:
Traceback (most recent call last):
  File "consumo-dia-anterior.py", line 11, in <module>
    connection.login("XXXXXXXX", "XXXXXXXXXXX")
  File "/home/pi/.local/lib/python2.7/site-packages/oligo/iber.py", line 33, in login
    raise ResponseException
oligo.exceptions.ResponseException

**Comment by hectorespert** [comment]
Que versiones usáis?

**Comment by pirracas77** [comment]
Acabo de reinstalar:

/home# pip install oligo
Collecting oligo
  Downloading oligo-1.3.1-py3-none-any.whl (8.2 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from oligo) (2.21.0)
Installing collected packages: oligo
Successfully installed oligo-1.3.1


`Traceback (most recent call last):
  File "test.py", line 4, in <module>
    connection.login("xxxxxx", "xxxxxxx")
  File "/usr/local/lib/python2.7/dist-packages/oligo/iber.py", line 33, in login
    raise ResponseException
oligo.exceptions.ResponseException`

**Comment by hectorespert** [comment]
Y ejecutandolo con `python3`?

**Comment by pirracas77** [comment]
Funciona!

`root@jeedom:/home/pruebas_oligo# python3 test.py

3295.11
`
