### ISSUE TITLE
TypeError: 'coroutine' object is not subscriptable

### ISSUE THREAD

**Issue by rafolas** [hectorespert/python-oligo#18]
I tried to read the consumption and since the script was not responding I broke the execution. Now I get these errors.  ("TypeError: 'coroutine' object is not subscriptable" and "Unclosed client session")
I understand that the unclosed client session is a matter of time but the other one I don't have any idea of what can it be solved.

 line 108, in watthourmeter
    return await self.measurement()["consumption"]
TypeError: 'coroutine' object is not subscriptable
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fca57225ed0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fca575ecad0>, 1.628017473)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fca575af450>

thanks for the tool!

**Comment by hectorespert** [comment]
Fixed in version 1.3.1
