### ISSUE TITLE
Tiene un problema y es el captcha de iberdrola

### ISSUE THREAD

**Issue by t4hor3** [hectorespert/python-oligo#2]
Lo e probado y funcionaba, pero se ve que como han detectado varios inicios de sesión seguidos ahora al usuario se le requiere un captcha por lo que el programa lanza un error que impide recoger datos.

**Comment by chimeno** [comment]
same error here

**Comment by jlopez77** [comment]
I have the same issue, recaptcha keeps blocking login attempts.
Also tryed with cUrl wih the same results.

**Comment by Jujonet** [comment]
Will be off in some hours without login attemps....

**Comment by jlopez77** [comment]
> Will be off in some hours without login attemps....

That doesn't solve the issue :laughing: 
Probably this should be solved by Iberdrola allowing access to the API without stupid restrictions.
