### ISSUE TITLE
CONSULTA - Límite de llamadas por día/hora

### ISSUE THREAD

**Issue by yayitazale** [hectorespert/python-oligo#26]
Hola: Lo primero gracias por el aporte.

En cuanto a la consulta, me gustaría saber si hay un límite conocido de llamadas por días/hora para no ser baneado.

Muchas gracias

**Comment by ghiki** [comment]
Yo desde el Home Assistant le estoy haciendo 2/h y sin problema, una cada 30 minutos para ver el consumo del contador, y además otra por día para consultar el consumo total desde el día 1 hasta hace 3 días (si pongo menos, me salen valores "Null" y luego Python da error al sumar para sacar los kW)

**Comment by yayitazale** [comment]
gracias
