### ISSUE TITLE
Consulta consumo energía reactiva

### ISSUE THREAD

**Issue by unaipuelles** [hectorespert/python-oligo#32]
Buenas Hector, en primer luagar darte las gracias por compartir este paquete ya que funciona divinamente.

Quería preguntar a ver si cabe la posibilidad de descargar al energía reactiva que se ha consumido en un contrato en específico. Actualmente se puede extraer de manera correcta la energía activa mediante `connection.consumption()` pero no he conseguido ninguna manera de obtener los datos de la reactiva.

Esta información actualmente se puede obtener (mediante la web) cuando se exporta un consumo mediante excel o csv en el apartado "Consumo registrado". Los datos serían la columna con el nombre "REACT Q1". He intentado de alguna manera extraer la información de las URLs a las que se llama para extraer esta información pero me ha sido imposible detectarlo.

Si necesitas cualquier información o ayuda me comentas sin problema. He visto todo el código y podría desarrollar esta parte si conseguimos de alguna manera la URL para acceder a esta información. 

Gracias de antemano y un saludo.

**Comment by hectorespert** [comment]
Prueba con `/consumidores/rest/consumoNew/obtenerDatosConsumoDH/06-02-2022/06-02-2022/horas/`

Por el tipo de contrato que tengo, creo que no puedo ver la parte de la energia reactiva.

**Comment by unaipuelles** [comment]
Buenas Hector, gracias por la rápida respuesta.

He probado a hacer la consulta y no me extrae los datos de la energía reactiva, si no que muestra la energía activa en Wh. Te adjunto el resultado de la llamada del json y el excel que me descargo desde la web para el día 03-01-2022.

Resultado de la llamada:
```
[{'cups': 'ESXXXXXXXXXXXXXXXXXX', 'fechaDesde': '03-01-2022', 'fechaHasta': '03-01-2022', 'periodos': ['Periodo 1', 'Periodo 2', 'Periodo 3', 'Periodo 4', 'Periodo 5', 'Periodo 6'], 'total': 628000.0, 'totalesPeriodosTarifarios': [312000.0, 255000.0, None, None, None, 61000.0], 'valores': [3000.0, 3000.0, 3000.0, 3000.0, 3000.0, 3000.0, 3000.0, 40000.0, 131000.0, 100000.0, 77000.0, 54000.0, 25000.0, 36000.0, 43000.0, 69000.0, 2000.0, 4000.0, 5000.0, 5000.0, 6000.0, 4000.0, 3000.0, 3000.0], 'valoresPeriodosTarifarios': [[None, None, None, None, None, 3000.0], [None, None, None, None, None, 3000.0], [None, None, None, None, None, 3000.0], [None, None, None, None, None, 3000.0], [None, None, None, None, None, 3000.0], [None, None, None, None, None, 3000.0], [None, None, None, None, None, 3000.0], [None, None, None, None, None, 40000.0], [None, 131000.0, None, None, None, None], [100000.0, None, None, None, None, None], [77000.0, None, None, None, None, None], [54000.0, None, None, None, None, None], [25000.0, None, None, None, None, None], [36000.0, None, None, None, None, None], [None, 43000.0, None, None, None, None], [None, 69000.0, None, None, None, None], [None, 2000.0, None, None, None, None], [None, 4000.0, None, None, None, None], [5000.0, None, None, None, None, None], [5000.0, None, None, None, None, None], [6000.0, None, None, None, None, None], [4000.0, None, None, None, None, None], [None, 3000.0, None, None, None, None], [None, 3000.0, None, None, None, None]], 'maximo': 131000.0, 'posicionMaximo': 8, 'periodoTarifarioMaximo': None}]
```

Resultado extraído desde la web:
[consumo_periodo_P1D_03-01-2022_03-01-2022.csv](https://github.com/hectorespert/python-oligo/files/8016652/consumo_periodo_P1D_03-01-2022_03-01-2022.csv)

Gracias de antemano y un saludo.

**Comment by hectorespert** [comment]
Cierro la issue si no se puede obtener
