### ISSUE TITLE
El valor total del contador no está disponible

### ISSUE THREAD

**Issue by alfonso-presa** [hectorespert/python-oligo#7]
Estaría bien tener acceso al valor total del contador, ya que ir acumulando cada cierto tiempo no garantiza que tengamos la foto total del consumo entre periodos (nos hemos podido perder variaciones).

He visto que confirmando la medición mediante POST a https://www.iberdroladistribucionelectrica.com/consumidores/rest/escenarioNew/confirmarMedicionOnLine/[valConsumo]/1/[idMedicion]

Luego GET a https://www.iberdroladistribucionelectrica.com/consumidores/rest/escenarioNew/obtenerEscenariosRest/

Recuperando el último dato en reponse.a.smps y haciendo POST a https://www.iberdroladistribucionelectrica.com/consumidores/rest/escenarioNew/obtenerEscenariosRestContador/
pasando como Payload `{nomEscenario: "[ID_OBTENIDO_DE_SMPS]"}`

devuelve el valor que tenía el contador en el momento de medición.
De cara a tener métricas incrementales y con buena precisión sin necesidad de hacer consultas muy frecuentes al API parece muy interesante.

Estoy intentando implementarlo, pero no soy muy de Python y la verdad es que igual intento hacerlo directamente con groovy desde mi SmartThings. Si al final lo hago sobre este repo, intentaré un PR.

**Comment by hectorespert** [comment]
@alfonso-presa Casi un año despues: https://github.com/hectorespert/python-oligo/pull/10

**Comment by alfonso-presa** [comment]
¡Buenísimo! ¡Gracias!

**Comment by zhapwey** [comment]
Could you give an example to read the total counter reading?
